name: Network Segmentation Demo CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Run network setup
        run: |
          sudo bash scripts/network_setup.sh > connectivity.log 2>&1 || true

      - name: Run network cleanup
        if: always()
        run: sudo bash scripts/network_cleanup.sh || true

      - name: Upload connectivity log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: connectivity-log
          path: connectivity.log

