name: Network Segmentation CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y iproute2 iptables net-tools bridge-utils shellcheck

      - name: Lint bash scripts
        run: |
          shellcheck scripts/*.sh || true

      - name: Run network setup
        run: |
          sudo bash scripts/network_setup.sh

      - name: Verify namespaces and IPs
        run: |
          echo ">>> Namespaces"
          ip netns list || true
          echo ">>> Interfaces"
          ip link show
          echo ">>> Guest namespace IP"
          sudo ip netns exec guestns ip addr show || true
          echo ">>> IoT namespace IP"
          sudo ip netns exec iotns ip addr show || true

      - name: Connectivity Tests
        run: |
          echo "### Running Connectivity Tests ###" | tee connectivity.log

          echo "Test 1: Primary -> Guest (should succeed)" | tee -a connectivity.log
          ping -c 2 10.10.10.2 | tee -a connectivity.log

          echo "Test 2: Primary -> IoT (should succeed)" | tee -a connectivity.log
          ping -c 2 10.10.10.3 | tee -a connectivity.log

          echo "Test 3: Guest -> IoT (should succeed)" | tee -a connectivity.log
          sudo ip netns exec guestns ping -c 2 10.10.10.3 | tee -a connectivity.log

          echo "Test 4: IoT -> Guest (should fail)" | tee -a connectivity.log
          if sudo ip netns exec iotns ping -c 2 -W 1 10.10.10.2; then
            echo "❌ IoT reached Guest (unexpected)" | tee -a connectivity.log
            exit 1
          else
            echo "✅ IoT could NOT reach Guest (expected)" | tee -a connectivity.log
          fi

          echo "Test 5: Guest -> Primary (should fail)" | tee -a connectivity.log
          if sudo ip netns exec guestns ping -c 2 -W 1 10.10.10.1; then
            echo "❌ Guest reached Primary (unexpected)" | tee -a connectivity.log
            exit 1
          else
            echo "✅ Guest could NOT reach Primary (expected)" | tee -a connectivity.log
          fi

          echo "Test 6: IoT -> Primary (should fail)" | tee -a connectivity.log
          if sudo ip netns exec iotns ping -c 2 -W 1 10.10.10.1; then
            echo "❌ IoT reached Primary (unexpected)" | tee -a connectivity.log
            exit 1
          else
            echo "✅ IoT could NOT reach Primary (expected)" | tee -a connectivity.log
          fi

      - name: Run network cleanup
        if: always()
        run: |
          sudo bash scripts/network_cleanup.sh

      - name: Upload logs (for debugging)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: connectivity-logs
          path: connectivity.log

