name: Connectivity Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup networks
        run: sudo bash scripts/network_setup.sh

      - name: Run connectivity tests
        run: |
          {
            echo "Running connectivity tests..."
            # Run each ping, but don't fail workflow on packet loss
            ping -c 3 10.10.10.3 || echo "Ping to 10.10.10.3 failed"
            ping -c 3 10.10.10.2 || echo "Ping to 10.10.10.2 failed"
            ping -c 3 10.10.10.4 || echo "Ping to 10.10.10.4 failed"
          } | tee connectivity.log

      - name: Cleanup
        if: always()
        run: sudo bash scripts/network_cleanup.sh

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: connectivity-results
          path: connectivity.log

