name: Network Segmentation CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up network
        run: sudo bash scripts/network_setup.sh

      - name: Run connectivity tests
        run: |
          set +e
          bash scripts/connectivity_tests.sh | tee connectivity.log
          set -e

      - name: Cleanup
        if: always()
        run: sudo bash scripts/network_cleanup.sh

      - name: Upload connectivity logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: connectivity-logs
          path: connectivity.log

