name: Network Segmentation CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y iproute2 iptables net-tools bridge-utils shellcheck

      - name: Lint bash scripts
        run: |
          shellcheck setup/*.sh teardown/*.sh || true

      - name: Run network setup
        run: |
          sudo bash setup/network_setup.sh

      - name: Verify namespaces and IPs
        run: |
          echo ">>> Namespaces"
          ip netns list
          echo ">>> Interfaces"
          ip link show
          echo ">>> Guest namespace IP"
          sudo ip netns exec guestns ip addr show
          echo ">>> IoT namespace IP"
          sudo ip netns exec iotns ip addr show

      - name: Connectivity Tests
        run: |
          echo "### Running Connectivity Tests ###"

          echo "Test 1: Primary -> Guest (should succeed)"
          ping -c 2 10.10.10.2

          echo "Test 2: Primary -> IoT (should succeed)"
          ping -c 2 10.10.10.3

          echo "Test 3: Guest -> IoT (should succeed)"
          sudo ip netns exec guestns ping -c 2 10.10.10.3

          echo "Test 4: IoT -> Guest (should fail)"
          if sudo ip netns exec iotns ping -c 2 -W 1 10.10.10.2; then
            echo "❌ IoT was able to reach Guest (unexpected)"
            exit 1
          else
            echo "✅ IoT could NOT reach Guest (expected)"
          fi

          echo "Test 5: Guest -> Primary (should fail)"
          if sudo ip netns exec guestns ping -c 2 -W 1 10.10.10.1; then
            echo "❌ Guest was able to reach Primary (unexpected)"
            exit 1
          else
            echo "✅ Guest could NOT reach Primary (expected)"
          fi

          echo "Test 6: IoT -> Primary (should fail)"
          if sudo ip netns exec iotns ping -c 2 -W 1 10.10.10.1; then
            echo "❌ IoT was able to reach Primary (unexpected)"
            exit 1
          else
            echo "✅ IoT could NOT reach Primary (expected)"
          fi

      - name: Run network cleanup
        if: always()
        run: |
          sudo bash teardown/network_cleanup.sh

      - name: Upload logs (for debugging)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: debug-logs
          path: /var/log

