name: Network Segmentation CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run network setup
        run: |
          set -e
          sudo bash scripts/network_setup.sh

      - name: Test connectivity (log-only)
        run: |
          set +e
          {
            echo "===== Connectivity Tests ====="

            echo
            echo "Guest → IoT (expected: ✅ works)"
            ip netns exec guestns ping -c 3 10.10.10.3

            echo
            echo "IoT → Guest (expected: ❌ blocked)"
            ip netns exec iotns ping -c 3 10.10.10.2

            echo
            echo "Host → Guest (expected: ✅ works)"
            ping -c 3 10.10.10.2

            echo
            echo "Host → IoT (expected: ✅ works)"
            ping -c 3 10.10.10.3

            echo "===== End of Tests ====="
          } | tee connectivity.log
          set -e

      - name: Cleanup
        if: always()
        run: sudo bash scripts/network_cleanup.sh

      - name: Upload connectivity log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: connectivity-results
          path: connectivity.log

